training:
    batch_size: 100
    n_epochs: 200
    ngpu: 1
    snapshot_freq: 10
    alpha: 0.5
    random_start: True
data:
    dataset: "CIFAR10"
    random_flip: False

    #dataset: "CIFAR10"
    #random_flip: True
optim:
    weight_decay: 5.0e-4
    optimizer: "SGD"
    lr: 0.001
